      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: devenrawat-bit
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00FFAA&color_dots=#1a1a1a,#222222,#444444,#888888

